// Code generated by https://github.com/chenxyzl/gsgen; DO NOT EDIT.
// gen_tools version: 1.2.0
// generate time: 2026-08-10 19:35:28
package bson

import (
	"encoding/json"
	"fmt"
	"github.com/chenxyzl/gsgen/gsmodel"
)

func (s *TestA) GetCc() *gsmodel.DList[int] {
	return s.cc
}
func (s *TestA) SetCc(v *gsmodel.DList[int]) {
	if v != nil {
		v.SetParent(0, s.UpdateDirty)
	}
	s.cc = v
	s.UpdateDirty(1 << 0)
}
func (s *TestA) GetDd() *gsmodel.DMap[string, *TestA] {
	return s.dd
}
func (s *TestA) SetDd(v *gsmodel.DMap[string, *TestA]) {
	if v != nil {
		v.SetParent(1, s.UpdateDirty)
	}
	s.dd = v
	s.UpdateDirty(1 << 1)
}
func (s *TestA) GetIgnoreMe() int64 {
	return s.ignoreMe
}
func (s *TestA) SetIgnoreMe(v int64) {
	s.ignoreMe = v
	s.UpdateDirty(1 << 2)
}
func (s *TestA) String() string {
	doc := struct {
		Cc       *gsmodel.DList[int]           `bson:"cc"`
		Dd       *gsmodel.DMap[string, *TestA] `bson:"dd"`
		IgnoreMe int64                         `bson:"-"`
	}{s.cc, s.dd, s.ignoreMe}
	return fmt.Sprintf("%v", &doc)
}
func (s *TestA) MarshalJSON() ([]byte, error) {
	doc := struct {
		Cc       *gsmodel.DList[int]           `bson:"cc"`
		Dd       *gsmodel.DMap[string, *TestA] `bson:"dd"`
		IgnoreMe int64                         `bson:"-"`
	}{s.cc, s.dd, s.ignoreMe}
	return json.Marshal(doc)
}
func (s *TestA) UnmarshalJSON(data []byte) error {
	doc := struct {
		Cc       *gsmodel.DList[int]           `bson:"cc"`
		Dd       *gsmodel.DMap[string, *TestA] `bson:"dd"`
		IgnoreMe int64                         `bson:"-"`
	}{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return err
	}
	s.SetCc(doc.Cc)
	s.SetDd(doc.Dd)
	s.SetIgnoreMe(doc.IgnoreMe)
	return nil
}
func (s *TestA) Clone() (*TestA, error) {
	return gsmodel.Clone(s)
}
