// Code generated by https://github.com/chenxyzl/gsgen; DO NOT EDIT.
// gen_tools version: 1.2.0
// generate time: 2026-08-10 19:35:28
package common

import (
	"encoding/json"
	"fmt"
	"github.com/chenxyzl/gsgen/gsmodel"
)

func (s *Common) String() string {
	doc := struct {
	}{}
	return fmt.Sprintf("%v", &doc)
}
func (s *Common) MarshalJSON() ([]byte, error) {
	doc := struct {
	}{}
	return json.Marshal(doc)
}
func (s *Common) UnmarshalJSON(data []byte) error {
	doc := struct {
	}{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return err
	}
	return nil
}
func (s *Common) Clone() (*Common, error) {
	return gsmodel.Clone(s)
}
